services:
  chat-app-front:
    build:
      context: ../../
      dockerfile: packages/front/Dockerfile.dev
    container_name: front
    ports:
      - 3000:3000
    env_file:
      - ../front/.env
  chat-app-back:
    build:
      context: ../../
      dockerfile: packages/server/Dockerfile
    container_name: api
    env_file:
      - ../server/config/prod.env
    ports:
      - 4000:4000
    restart: always
  db:
    container_name: db
    image: postgres:alpine
    # Comment out the ports line if you don't want to expose the database port in production (no need for external access, the api will connect to it internally)
    #ports:
      #- 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always

# volumes:

networks:
  default:
    name: local-network
