global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change log level and format here ...
#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
#     - format: [common, json]
# log:
#  level: DEBUG
#  format: common
#  filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable accesslog and change format here ...
#     - format: [common, json]
# accesslog:
#   format: common
#   filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  # disableDashboardAd: true
  # insecure: true
log:
  level: DEBUG
  format: common
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  fields:
    defaultMode: drop
    names:
      ClientHost: keep
      RequestHost: keep
      RequestMethod: keep
      RequestPath: keep
    headers:
      defaultMode: drop
      names:
        Date: keep
        Cf-Connecting-Ip: keep
        Cf-Pseudo-Ipv4: keep
        X-Real-Ip: keep

  filePath: /var/log/traefik/access.log

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true

  # -- (Optional) Add custom Entrypoint
  # custom:
  #   address: :8081

# -- Configure your CertificateResolver here...
certificatesResolvers:
  cloudflare:
    acme:
      email: email@example.com # Change this to your email
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    exposedByDefault: false

  file:
    directory: /etc/traefik
    watch: true

serversTransport:
  insecureSkipVerify: true
